#!/usr/bin/env sh
. ./.gamesrc/config

# git hook
/bin/rm .git/hooks/ -rf
cp -r $hooks .git/hooks

# clean tmp file
$bin/cleandata

echo 0 > $data/merge
$bin/gentask 1

if [ -n "`git show-ref refs/heads/feature1`" ]; then
	git branch -d feature1
fi

if [ -n "`git show-ref refs/heads/feature2`" ]; then
	git branch -d feature2
fi
