#!/usr/bin/env sh
. ./.gamesrc/config

# git hook
/bin/rm .git/hooks/ -rf
cp -r $hooks .git/hooks

# clean tmp file
$bin/cleandata

echo 0 > $data/merge
$bin/gentask 1

git branch -d feature1
git branch -d feature2
